### ISSUE TITLE
Enhancement request: Adding a blocked workers list

### ISSUE THREAD

**Issue by interactiveaudiolab** [reseval/reseval#29]
If someone wants to run a study incrementally (e.g. run it on 100 people....then run it later on 100 more), it would help to be able to add a list of blocked MTurk workerIDs so that the second run could be sure to get completely different participants.

**Comment by maxrmorrison** [comment]
I forgot that I had already fixed this issue. Extensions add assignments to the same HIT, and the same participant can't take the same HIT more than once. So we'll always get different participants.
