### ISSUE TITLE
Question about using reseval.create

### ISSUE THREAD

**Issue by RBenita** [reseval/reseval#39]
Hey,

I hope it is ok Im writing here- 
While trying to use reseval.create with aws, it seems that the condition:
response['Status'].lower() != 'ready':
is always with the values "lunching" or "terminate" and it just stay on the environment build loop..
there is maybe a reason for that? 
thank you,

Roi

**Comment by maxrmorrison** [comment]
Hi Roi! Two few questions:  (1) Have you verified that everything works either locally or with Heroku? Note that the version of Node being used recently changed. I just realized I hadn't updated the README with the new version--that's fixed. (2) Have you checked the AWS elastic beanstalk console for information about the environment? Sometimes there is good debugging info there.

**Comment by RBenita** [comment]
Hey max,
Thanks for the quick response!
I think that the link you attached solved the problem (opening a role with the 3 policies, opening manually the first environment in my Elastic-beanstalk account) 
Unfortunately, Im still facing some problems:
- firstly I got this problem:
![image](https://github.com/reseval/reseval/assets/73468214/d9744251-0b56-49c8-8069-234449e16b62)
and it seems that adding the policy :  AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy solved it..

-Now I get this kind of problem:
![image](https://github.com/reseval/reseval/assets/73468214/5a394efb-f16d-4372-bb91-493514a27fc8)
and I'm not sure what next :/ It seems that there is still a problem with the connection to AWS..

Roi

**Comment by RBenita** [comment]
Hey max,
Thanks for the quick response!
I think that the link you attached solved the problem (opening a role with the 3 policies, opening manually the first environment in my Elastic-beanstalk account)
Unfortunately, Im still facing some problems:

While It seems that the environment in AWS is open correctly, I get this kind of messages during the Create process:
![image](https://github.com/reseval/reseval/assets/73468214/ef43ae21-e6a5-48f2-9f41-51ff384f773c)

Do you have any Idea why it happens?

Thanks again,
Roi

**Comment by maxrmorrison** [comment]
Hi Roi,

There's not enough information for me to tell what's happening yet. Googling that error, some people report a bad version of `urllib` or `openssl` can cause that. Another mentioned intermittent internet issues. That stack trace you posted doesn't show any `reseval` call. If you happen to know what part of creation this occurred during, that might help. And the AWS console may have further information. Lastly, as a matter of security, the IP address used to initialize the server is the one that is expected to also initialize the database and perform any monitoring, deletion, etc. So you might double check that is the case.

As for local/remote/production, remote is default and production is used when the `--production` flag is added. See [this section of the docs](https://github.com/reseval/reseval#create).

**Comment by RBenita** [comment]
Hi Max,
Sorry for the late responding and thanks for your comment.
I checked the code again, and it seems that there is a problem with that part:
![image](https://github.com/reseval/reseval/assets/73468214/e718ea40-1921-43b8-859e-ef9fcfbf5203)
It appears on /database/aws.py
and this is the error:
![image](https://github.com/reseval/reseval/assets/73468214/d0dd7018-f874-4bbf-a2f9-8276ad1086d4)
Im not sure, maybe it is a proxy problem? 
Thank you in advance,
Roi.

**Comment by RBenita** [comment]
Hi,
Change it to: "https://api.seeip.org/jsonip?" solved this problem.

**Comment by maxrmorrison** [comment]
That works for me as well--and it seems to be what seeip.org recommends. Feel free to place a pull request. Otherwise, I'll add that to next release.

**Comment by maxrmorrison** [comment]
I made a new release to fix the other bug you mentioned and rolled this out in the process. Released in version 0.1.1. Thanks again!
