### ISSUE TITLE
Question about working with MTurk developer Sandbox

### ISSUE THREAD

**Issue by RBenita** [reseval/reseval#40]
Hi,
I have two questions regarding Reseval and I would really appreciate any help with them:
1. While try working with the MTurk Sandbox, I am succeeding to run the reseval.create but there is a weird behavior:
In the opened environment on AWS, I can see the application which I had opened, and it looks like that:
<img width="1136" alt="image" src="https://github.com/reseval/reseval/assets/73468214/8d5d3cdc-fd48-4600-bce0-c02626baa4d9">
But, on the AWS mturk worker page, the whole HIT is looks like: 

![image](https://github.com/reseval/reseval/assets/73468214/52ccde23-341f-4e59-9820-ad8cb00300c5)

After accepting the request, I tried to click the link but I get this page:

<img width="526" alt="image" src="https://github.com/reseval/reseval/assets/73468214/f776e4f3-fc43-4b22-ae6b-5b760f835cbd">

I was wondering maybe the sandbox platform is not support with opening that kind of html files?

2. While using MUSHRA test, on the prescreen_questions, There is a wav file which I need to upload? If not, from where Reseval brings that file? for now, it looks like that on the application page in AWS: 
<img width="1072" alt="image" src="https://github.com/reseval/reseval/assets/73468214/6ae7a2c7-4d91-4e94-8180-bbed8b2d8c53">

Thank you very much,
Roi

**Comment by maxrmorrison** [comment]
For 1) the MTurk display looks correct. There will be a survey link at the end of the eval. Participants are instructed to copy-paste that link into MTurk. However, you've caught a bug that I have not formatted that URL correctly. I'll take a look at that today/tomorrow. The Heroku backend should work if you need to run something in the meantime (although it gave me some issues a few months ago which prompted the change to AWS). 

For 2) you pass the directory to use to `reseval.create`. The directory should be formatted [as described here](https://github.com/reseval/reseval#mushra).

**Comment by maxrmorrison** [comment]
Nevermind, this issue is still ongoing. Currently working on it.

**Comment by maxrmorrison** [comment]
Figured it out. The URL also needs to be prefixed with `http://`. Fixed in version 0.1.2.
